{{- $fullName := include "pvc-exporter.fullname" . -}}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $fullName }}
    release: prome
    {{- if .Values.serviceMonitor.additionalLabels }}
      {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
  name: {{ $fullName }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}
      version: {{ .Chart.AppVersion }}
  endpoints:
  - interval: 30s
    targetPort: metrics
    scheme: http
    path: /
  jobLabel: app
{{- end}}